export const RAW_WORD_LIST = `1. mature (词频) /mə'tjuər/ (词性). 成熟的；深思熟虑的
2. supreme (词频) /suː'priːm/ (词性). 至高无上的
3. likely (词频) /'laɪkli/ (词性). 可能的
4. interaction (词频) /ˌɪntər'ækʃən/ (词性). 互动；交互
5. construction (词频) /kən'strʌkʃən/ (词性). 建设；建造
6. previous (词频) /'priːviəs/ (词性). 以前的；先前的
7. material (词频) /mə'tɪəriəl/ (词性). 材料；物质
8. gym (词频) /dʒɪm/ (词性). 健身房
9. responsible (词频) /rɪ'spɒnsəbl/ (词性). 负责的
10. rare (词频) /reər/ (词性). 稀有的；罕见的
11. contact (词频) /'kɒntækt/ (词性). 接触；联系
12. tend (词频) /tend/ (词性). 倾向于；易于
13. current (词频) /'kʌrənt/ (词性). 当前的；流行的
14. individual (词频) /ˌɪndɪ'vɪdʒuəl/ (词性). 个人；个体
15. factor (词频) /'fæktər/ (词性). 因素
16. action (词频) /'ækʃən/ (词性). 行动；行为
17. access (词频) /'ækses/ (词性). 访问；通道
18. career (词频) /kə'rɪər/ (词性). 职业；生涯
19. offer (词频) /'ɒfər/ (词性). 提供；提议
20. budget (词频) /'bʌdʒɪt/ (词性). 预算
21. whether (词频) /'weðər/ (词性). 是否
22. challenge (词频) /'tʃælɪndʒ/ (词性). 挑战；质疑
23. employer (词频) /ɪm'plɔɪər/ (词性). 雇主
24. register (词频) /'redʒɪstər/ (词性). 注册；登记
25. benefit (词频) /'benɪfɪt/ (词性). 利益；好处
26. rather (词频) /'rɑːðər/ (词性). 相当；宁可
27. expand (词频) /ɪk'spænd/ (词性). 扩展；扩大
28. prime (词频) /praɪm/ (词性). 主要的；首要的
29. interview (词频) /'ɪntərvjuː/ (词性). 面试；访谈
30. policy (词频) /'pɒləsi/ (词性). 政策；方针
31. rate (词频) /reɪt/ (词性). 比率；速率
32. imply (词频) /ɪm'plaɪ/ (词性). 暗示；意味
33. inevitable (词频) /ɪ'nevɪtəbl/ (词性). 不可避免的
34. saving (词频) /'seɪvɪŋ/ (词性). 储蓄；节省
35. yield (词频) /jiːld/ (词性). 产生；屈服
36. connect (词频) /kə'nekt/ (词性). 连接；联系
37. exceptional (词频) /ɪk'sepʃənl/ (词性). 杰出的
38. coach (出现9次) /koʊtʃ/ n. 教练；辅导员
39. scholarship (出现9次) /'skɒləʃɪp/ n. 奖学金
40. campus (出现21次) /'kæmpəs/ n. 校园
41. superficial (出现5次) /ˌsuːpər'fɪʃəl/ a. 表面的
42. feasible (出现6次) /'fiːzəbl/ a. 可行的；可能的
43. acknowledge (出现15次) /ək'nɒlɪdʒ/ v. 承认；认可
44. vote (出现17次) /voʊt/ v. 投票；表决
45. cash (出现17次) /kæʃ/ n. 现金
46. outer (出现13次) /'aʊtər/ a. 外部的；外面的
47. admission (出现11次) /əd'mɪʃən/ n. 录取；准许进入
48. natural (出现31次) /'nætʃərəl/ a. 自然的；天然的
49. simply (出现56次) /'sɪmpli/ adv. 简单地；仅仅
50. patience (出现12次) /'peɪʃəns/ n. 耐心；忍耐
51. essential (出现28次) /ɪ'senʃəl/ a. 必要的；基本的
52. oxygen (出现13次) /'ɒksɪdʒən/ n. 氧气
53. lunar (出现10次) /'luːnər/ a. 阴历的；月球的
54. underline (出现6次) /ˌʌndər'laɪn/ v. 强调
55. intelligence (出现39次) /ɪn'telɪdʒəns/ n. 智力；智慧
56. impose (出现11次) /ɪm'poʊz/ v. 强加；施加
57. performance (出现71次) /pər'fɔːrməns/ n. 表现
58. internal (出现13次) /ɪn'tɜːrnl/ a. 内部的；国内的
59. semester (词频) /sɪ'mestər/ (词性). 学期
60. pose (词频) /poʊz/ (词性). 摆姿势；提出
61. frustrate (词频) /'frʌstreɪt/ (词性). 挫败；使沮丧
62. principal (词频) /'prɪnsəpl/ (词性). 主要的；校长
63. volcano (词频) /vɒl'keɪnoʊ/ (词性). 火山
64. diverse (词频) /daɪ'vɜːrs/ (词性). 多样的；不同的
65. typical (词频) /'tɪpɪkl/ (词性). 典型的；通常的
66. initiative (词频) /ɪ'nɪʃətɪv/ (词性). 主动性；倡议
67. assumption (词频) /ə'sʌmpʃən/ (词性). 假设；设想
68. effective (词频) /ɪ'fektɪv/ (词性). 有效的
69. tuition (词频) /tuː'ɪʃən/ (词性). 学费；教学
70. revenue (词频) /'revənjuː/ (词性). 收入；税收
71. risk (词频) /rɪsk/ (词性). 风险
72. bias (词频) /'baɪəs/ (词性). 偏见；偏向
73. supervise (词频) /'suːpərvaɪz/ (词性). 监督；管理
74. employee (词频) /ˌem'plɔɪiː/ (词性). 雇员；员工
75. potential (词频) /pə'tenʃəl/ (词性). 潜在的；可能的
76. principle (词频) /'prɪnsəpl/ (词性). 原则；原理
77. anyway (词频) /'eniweɪ/ (词性). 无论如何；总之
78. decline (词频) /dɪ'klaɪn/ (词性). 下降；拒绝
79. privacy (词频) /'praɪvəsi/ (词性). 隐私`;
